title: Sudoker
tagline: a user-friendly open source sudoku solver and generator (currently in alpha phase)
description: a user-friendly open source sudoku solver and generator (currently in alpha phase)
author: Shayna003
remote_theme: pages-themes/midnight@v0.2.0
description: > # this means to ignore newlines until "baseurl:"
  A user friendly open-source sudoku solver and generator, curretnly in alpha phase
# social links
show_excerpts: true # set to false to remove excerpts on the homepage
show_downloads: true
plugins:
- jekyll-remote-theme 
