title: Sudoker
tagline: an open source sudoku solver and generator
description: an open source sudoku solver and generator coded in Java, in its alpha phase
author: Shayna003
theme: jekyll-theme-not-pure-poole
description: > # this means to ignore newlines until "baseurl:"
  An open-source sudoku solver and generator.
# social links
show_excerpts: true # set to false to remove excerpts on the homepage
