title: Sudoker
tagline: a user-friendly open source sudoku solver and generator (currently in alpha phase)
description: a user-friendly open source sudoku solver and generator (currently in alpha phase)
author: Shayna003
theme: jekyll-theme-midnight
description: > # this means to ignore newlines until "baseurl:"
  An open-source sudoku solver and generator.
# social links
show_excerpts: true # set to false to remove excerpts on the homepage
